#Numpy, libreria para ciencia de datos

In [1]:
import numpy as np 
#pip install numpy

In [ ]:
def creaArray(fila,columna):
  array = np.random.random((fila,columna))
  return array

In [ ]:
array_1d=np.array([1,4,3])
print(array_1d)


[1 4 3]


In [ ]:
array_1d

array([1, 4, 3])

In [ ]:
array_2d=np.array([(1,4,2),(5,2,3)])
array_2d

array([[1, 4, 2],
       [5, 2, 3]])

In [ ]:
array_3d=np.array([[(1.6,4.5,2),(1,5.8,9)],[(7,5,9.3),(8,1.4,3)],[(3,5,3),(7,2,9)]],dtype=float)
array_3d

array([[[1.6, 4.5, 2. ],
        [1. , 5.8, 9. ]],

       [[7. , 5. , 9.3],
        [8. , 1.4, 3. ]],

       [[3. , 5. , 3. ],
        [7. , 2. , 9. ]]])

In [ ]:
print(array_3d)

[[[1.6 4.5 2. ]
  [1.  5.8 9. ]]

 [[7.  5.  9.3]
  [8.  1.4 3. ]]

 [[3.  5.  3. ]
  [7.  2.  9. ]]]


#Creando Arrays

In [ ]:
#De ceros con 3 filas y 4 columnas
array_ceros=np.zeros((3,4))
array_ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#De unos con 2 dimensiones 4 filas 5 columnas
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
#Intervalo y saltos
np.arange(12,31,2)

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
#Intervalo y divisiones
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

In [ ]:
#Valor dado
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
#Matriz identidad, diagonal de unos
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Valores aleatorios entre 0 y 1
np.random.random((4,4))

array([[0.75285211, 0.11858646, 0.36126724, 0.45727286],
       [0.25994762, 0.61445816, 0.76870491, 0.91567557],
       [0.85643901, 0.57397506, 0.15088249, 0.40463163],
       [0.59626211, 0.53078446, 0.59686667, 0.35896276]])

In [ ]:
#Vacio de 4 filas y 3 columnas
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#Grabar y cargar

In [ ]:
#Grabar
#np.save('mi_array',np.random.random((3,3)))
np.save('mi_array_3d',array_3d)

In [ ]:
#Cargar
mi_array=np.load('mi_array_3d.npy')
mi_array

array([[[1.6, 4.5, 2. ],
        [1. , 5.8, 9. ]],

       [[7. , 5. , 9.3],
        [8. , 1.4, 3. ]],

       [[3. , 5. , 3. ],
        [7. , 2. , 9. ]]])

In [ ]:
#Grabar a fichero de texto
np.savetxt('mi_array.txt',array_2d,delimiter=" ")

In [ ]:
#Cargar de fichero de texto
array_2d=np.loadtxt('mi_array.txt')
print(array_2d)

[[1. 4. 2.]
 [5. 2. 3.]]


#Tipos de datos

In [ ]:
#Enteros
np.int64

numpy.int64

In [ ]:
#Decimal, numero doble precision o de punto flotante
np.float64

numpy.float64

In [ ]:
#Complejos
np.complex_

numpy.complex128

In [ ]:
#Boolean
np.bool_

numpy.bool_

In [ ]:
#Objetos
np.object_

numpy.object_

In [ ]:
#Cadenas
np.string_

numpy.bytes_

In [ ]:
np.unicode_

numpy.str_

#Propiedades y caracteristicas

In [ ]:
array_3d

array([[[1.6, 4.5, 2. ],
        [1. , 5.8, 9. ]],

       [[7. , 5. , 9.3],
        [8. , 1.4, 3. ]],

       [[3. , 5. , 3. ],
        [7. , 2. , 9. ]]])

In [ ]:
#Dimension o forma
array_3d.shape

(3, 2, 3)

In [ ]:
#Longitud
len(array_3d)

3

In [ ]:
#Numero de dimensiones
array_3d.ndim

3

In [ ]:
#Tamaño o numero de elementos
array_3d.size

18

In [ ]:
#Tipos de datos
array_3d.dtype

dtype('float64')

In [ ]:
array_3d.dtype.name

'float64'

In [ ]:
#Convertir de un tipo a otro
array_3d.astype(int)

array([[[1, 4, 2],
        [1, 5, 9]],

       [[7, 5, 9],
        [8, 1, 3]],

       [[3, 5, 3],
        [7, 2, 9]]])

#Ayuda

In [ ]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


#Operadores Aritmeticos

In [ ]:
#Arrays de ejemplos
array1=np.random.random((4,4))
array1

array([[0.76834816, 0.2869861 , 0.07228661, 0.52983716],
       [0.79565618, 0.31725566, 0.17553004, 0.15171423],
       [0.49734136, 0.33177043, 0.79473864, 0.88514113],
       [0.26725948, 0.25622415, 0.13606846, 0.79389823]])

In [ ]:
array2=np.random.random((4,4))
array2

array([[0.3168319 , 0.23177337, 0.94337712, 0.35230628],
       [0.40665201, 0.13565838, 0.64535998, 0.08795513],
       [0.14624175, 0.55623124, 0.42355026, 0.59263804],
       [0.50156974, 0.94113118, 0.74476194, 0.35098769]])

In [ ]:
#Suma
array3=array1+array2
array3

array([[1.08518006, 0.51875947, 1.01566373, 0.88214344],
       [1.20230819, 0.45291404, 0.82089002, 0.23966936],
       [0.64358311, 0.88800167, 1.2182889 , 1.47777917],
       [0.76882922, 1.19735534, 0.8808304 , 1.14488592]])

In [ ]:
#Otra opcion de suma
array3=np.add(array1,array2)
array3

array([[1.08518006, 0.51875947, 1.01566373, 0.88214344],
       [1.20230819, 0.45291404, 0.82089002, 0.23966936],
       [0.64358311, 0.88800167, 1.2182889 , 1.47777917],
       [0.76882922, 1.19735534, 0.8808304 , 1.14488592]])

In [ ]:
#Resta
array3=array1-array2
array3

array([[ 0.45151626,  0.05521273, -0.87109051,  0.17753088],
       [ 0.38900417,  0.18159728, -0.46982993,  0.0637591 ],
       [ 0.35109961, -0.22446081,  0.37118838,  0.29250309],
       [-0.23431026, -0.68490703, -0.60869347,  0.44291054]])

In [ ]:
#Multiplica
array3=np.multiply(array1,array2)
array3

array([[0.24343721, 0.06651574, 0.06819353, 0.18666496],
       [0.32355518, 0.04303839, 0.11328007, 0.01334405],
       [0.07273207, 0.18454108, 0.33661176, 0.5245683 ],
       [0.13404927, 0.24114054, 0.10133861, 0.2786485 ]])

In [ ]:
#Divide
array3=array1/array2
array3

array([[2.4250972 , 1.23821861, 0.07662536, 1.50391063],
       [1.95660213, 2.33863665, 0.27198781, 1.72490481],
       [3.40081657, 0.59646133, 1.87637386, 1.49356111],
       [0.53284611, 0.27225126, 0.18270061, 2.26189767]])

In [ ]:
array3=np.divide(array1,array2)
array3

array([[2.4250972 , 1.23821861, 0.07662536, 1.50391063],
       [1.95660213, 2.33863665, 0.27198781, 1.72490481],
       [3.40081657, 0.59646133, 1.87637386, 1.49356111],
       [0.53284611, 0.27225126, 0.18270061, 2.26189767]])

In [ ]:
np.exp(array1)

array([[2.15620161, 1.33240569, 1.07496339, 1.69865568],
       [2.21589455, 1.37335364, 1.1918778 , 1.1638276 ],
       [1.64434374, 1.39343292, 2.2138623 , 2.42332636],
       [1.30637939, 1.29204231, 1.14576033, 2.21200254]])

In [ ]:
np.sin(array1)

array([[0.69494841, 0.28306288, 0.07222367, 0.50539284],
       [0.71432297, 0.31196036, 0.17463006, 0.15113289],
       [0.47709067, 0.32571742, 0.71368055, 0.77400435],
       [0.26408921, 0.25342979, 0.13564897, 0.71309162]])

In [ ]:
np.cos(array2)

array([[0.95022723, 0.97326058, 0.58705745, 0.9385794 ],
       [0.91845022, 0.9908125 , 0.7988833 , 0.99613444],
       [0.98932572, 0.849251  , 0.91163553, 0.82947009],
       [0.87682891, 0.58887415, 0.73524928, 0.93903358]])

In [ ]:
np.log(array2)

array([[-1.14938392, -1.46199523, -0.05828916, -1.04325436],
       [-0.89979748, -1.99761546, -0.43794701, -2.43092845],
       [-1.92249421, -0.58657117, -0.85908309, -0.52317146],
       [-0.69001262, -0.06067274, -0.29469066, -1.04700414]])

In [ ]:
#Producto de matrices
array1.dot(array2)

array([[0.63646229, 0.75586906, 1.33527098, 0.5247419 ],
       [0.482867  , 0.46786859, 1.14268473, 0.46549454],
       [0.85267269, 1.4353703 , 1.679123  , 0.98606338],
       [0.60696461, 0.9195505 , 1.06638031, 0.47598127]])

#Comparacion

== != < > <= >= and or

In [ ]:
array1==array2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
array1<0.5

array([[False,  True,  True, False],
       [False,  True,  True,  True],
       [ True,  True, False, False],
       [ True,  True,  True, False]])

In [ ]:
array1

array([[0.76834816, 0.2869861 , 0.07228661, 0.52983716],
       [0.79565618, 0.31725566, 0.17553004, 0.15171423],
       [0.49734136, 0.33177043, 0.79473864, 0.88514113],
       [0.26725948, 0.25622415, 0.13606846, 0.79389823]])

In [ ]:
array3<=0.4

array([[False, False,  True, False],
       [False, False,  True, False],
       [False, False, False, False],
       [False,  True,  True, False]])

In [ ]:
array3

array([[2.4250972 , 1.23821861, 0.07662536, 1.50391063],
       [1.95660213, 2.33863665, 0.27198781, 1.72490481],
       [3.40081657, 0.59646133, 1.87637386, 1.49356111],
       [0.53284611, 0.27225126, 0.18270061, 2.26189767]])

#Estadisticos basicos y otras funciones

In [ ]:
array1=creaArray(5,5)
array1

array([[0.38793276, 0.60208478, 0.41808967, 0.24413013, 0.38481288],
       [0.75877891, 0.73657283, 0.91950851, 0.19491846, 0.88286669],
       [0.29510897, 0.57773786, 0.41387761, 0.28965302, 0.43109872],
       [0.41478154, 0.74847598, 0.61011024, 0.49912118, 0.69955266],
       [0.47464506, 0.06518268, 0.85021389, 0.94827922, 0.93655626]])

In [ ]:
sumaTotal=array1.sum()
print(sumaTotal)

13.784090504202645


In [ ]:
array1.min()

0.06518268440445318

In [ ]:
array1.max()

0.9482792211402644

In [ ]:
#Maximo por filas
array1.max(axis=0)

array([0.75877891, 0.74847598, 0.91950851, 0.94827922, 0.93655626])

In [ ]:
#Maximo por columnas
array1.max(axis=1)

array([0.60208478, 0.91950851, 0.57773786, 0.74847598, 0.94827922])

In [ ]:
#Suma acumulada
array1.cumsum(axis=1)

array([[0.38793276, 0.99001753, 1.4081072 , 1.65223733, 2.03705021],
       [0.75877891, 1.49535175, 2.41486026, 2.60977871, 3.4926454 ],
       [0.29510897, 0.87284683, 1.28672444, 1.57637746, 2.00747618],
       [0.41478154, 1.16325751, 1.77336776, 2.27248894, 2.9720416 ],
       [0.47464506, 0.53982774, 1.39004163, 2.33832085, 3.27487712]])

In [ ]:
array1

array([[0.38793276, 0.60208478, 0.41808967, 0.24413013, 0.38481288],
       [0.75877891, 0.73657283, 0.91950851, 0.19491846, 0.88286669],
       [0.29510897, 0.57773786, 0.41387761, 0.28965302, 0.43109872],
       [0.41478154, 0.74847598, 0.61011024, 0.49912118, 0.69955266],
       [0.47464506, 0.06518268, 0.85021389, 0.94827922, 0.93655626]])

In [ ]:
#Media
np.mean(array1)

0.5513636201681058

In [ ]:
#Mediana
np.median(array1)

0.49912118185757104

In [ ]:
#Correlacion
np.corrcoef(array1)

array([[ 1.        ,  0.5791216 ,  0.89361353,  0.66191911, -0.8355748 ],
       [ 0.5791216 ,  1.        ,  0.46901381,  0.40788429, -0.19252115],
       [ 0.89361353,  0.46901381,  1.        ,  0.92154485, -0.59116887],
       [ 0.66191911,  0.40788429,  0.92154485,  1.        , -0.2545396 ],
       [-0.8355748 , -0.19252115, -0.59116887, -0.2545396 ,  1.        ]])

In [ ]:
#Desviacion
np.std(array1)

0.24579103753282674

#Copiando arrays

In [6]:
array1=np.random.randint(21,size=(4,4))
array1

array([[12, 10, 14, 16],
       [15,  0,  1,  2],
       [20, 20,  6,  7],
       [ 4, 10, 20, 11]])

In [7]:
#Crea una imagen del array, el valor cambiado se refleja en los dos
array_cop=array1.view()
array_cop

array([[12, 10, 14, 16],
       [15,  0,  1,  2],
       [20, 20,  6,  7],
       [ 4, 10, 20, 11]])

In [8]:
np.array_equal(array1,array_cop)

True

In [12]:
#Modificamos un valor de la copia
array_cop[0,1]=99
array_cop

array([[12, 99, 14, 16],
       [15,  0,  1,  2],
       [20, 20,  6,  7],
       [ 4, 10, 20, 11]])

In [13]:
#Modificamos un valor del original
array1[1,2]=88
array1

array([[12, 99, 14, 16],
       [15,  0, 88,  2],
       [20, 20,  6,  7],
       [ 4, 10, 20, 11]])

In [14]:
array_cop

array([[12, 99, 14, 16],
       [15,  0, 88,  2],
       [20, 20,  6,  7],
       [ 4, 10, 20, 11]])

In [15]:
#Creamos copia independiente
array_cop2 = np.copy(array1)
array_cop2

array([[12, 99, 14, 16],
       [15,  0, 88,  2],
       [20, 20,  6,  7],
       [ 4, 10, 20, 11]])

In [16]:
array_cop2[2,3]=77
array_cop2

array([[12, 99, 14, 16],
       [15,  0, 88,  2],
       [20, 20,  6, 77],
       [ 4, 10, 20, 11]])

In [17]:
array1

array([[12, 99, 14, 16],
       [15,  0, 88,  2],
       [20, 20,  6,  7],
       [ 4, 10, 20, 11]])

In [19]:
array_cop2 = array1 * 3
array_cop2

array([[ 36, 297,  42,  48],
       [ 45,   0, 264,   6],
       [ 60,  60,  18,  21],
       [ 12,  30,  60,  33]])

In [20]:
array1

array([[12, 99, 14, 16],
       [15,  0, 88,  2],
       [20, 20,  6,  7],
       [ 4, 10, 20, 11]])

In [21]:
array_cop2=array1.copy()
array_cop2

array([[12, 99, 14, 16],
       [15,  0, 88,  2],
       [20, 20,  6,  7],
       [ 4, 10, 20, 11]])

In [22]:
array1

array([[12, 99, 14, 16],
       [15,  0, 88,  2],
       [20, 20,  6,  7],
       [ 4, 10, 20, 11]])

In [23]:
np.array_equal(array1,array_cop2)

True

#Arrays, ordenamiento

In [37]:
array_1 = np.random.randint(41,size=(10,10))
array_1

array([[30, 20, 23, 29, 25, 33,  1, 32,  3, 13],
       [29, 27,  9,  3, 22, 23, 11,  7, 24, 33],
       [ 9, 30,  4, 24,  4, 37, 24, 26,  2, 25],
       [23, 10, 29, 31,  1, 21,  9, 27,  1, 35],
       [13,  9, 23, 16,  6, 34,  7,  0, 36, 24],
       [37, 22, 12, 31, 38, 35, 16, 32, 35, 12],
       [34, 30, 19, 26, 32, 35, 13, 35, 34, 14],
       [40,  5, 16, 20, 40, 33, 33,  9,  5, 27],
       [40, 37, 23,  7, 22, 17, 15, 18, 40,  5],
       [ 6, 32, 19, 26,  9,  9, 21, 22, 33, 25]])

In [40]:
array_2 = np.random.randint(31,size=(10,10))
array_2

array([[ 2,  8, 17,  9, 30, 17, 11,  5, 19,  4],
       [26, 12, 20,  5, 11, 23,  2, 30, 30, 23],
       [16, 16, 17,  3,  3,  5, 25,  9, 12, 11],
       [ 6, 27,  4, 25,  2, 14, 29, 12, 16, 28],
       [21,  5,  9, 14,  0,  7,  9, 30, 15, 10],
       [ 4,  5,  3, 16, 26, 26,  6, 23, 30, 25],
       [24,  0, 13,  6,  2, 16, 27,  1, 13,  3],
       [24,  3, 12, 30, 10, 12,  3, 14, 17, 15],
       [12, 24, 30, 22, 15,  9, 11, 11, 29,  0],
       [18,  7, 15, 29, 28, 29, 14, 17,  6, 12]])

In [26]:
array_1

array([[28, 27,  7, 17,  6,  1,  2, 19, 10, 25],
       [23, 33, 39, 27,  1, 30, 33, 15, 10, 40],
       [ 5,  5, 28,  1, 10, 11, 30,  1, 34,  3],
       [ 6, 16,  6, 15, 23, 38,  6, 36,  7,  2],
       [ 3,  7, 20, 27, 35, 19, 30, 19, 21, 28],
       [11,  3,  7,  0, 19, 17, 32, 12, 27, 40],
       [ 0,  0, 40, 23, 38, 39, 23, 38, 34, 21],
       [27, 22, 26,  8,  4, 21, 36,  3, 32,  4],
       [15, 31, 13, 11, 29, 19, 16, 24, 17, 10],
       [ 1,  8, 40,  6, 12, 27, 11, 33, 18, 12]])

In [28]:
array_1.sort()
array_1

array([[ 1,  2,  6,  7, 10, 17, 19, 25, 27, 28],
       [ 1, 10, 15, 23, 27, 30, 33, 33, 39, 40],
       [ 1,  1,  3,  5,  5, 10, 11, 28, 30, 34],
       [ 2,  6,  6,  6,  7, 15, 16, 23, 36, 38],
       [ 3,  7, 19, 19, 20, 21, 27, 28, 30, 35],
       [ 0,  3,  7, 11, 12, 17, 19, 27, 32, 40],
       [ 0,  0, 21, 23, 23, 34, 38, 38, 39, 40],
       [ 3,  4,  4,  8, 21, 22, 26, 27, 32, 36],
       [10, 11, 13, 15, 16, 17, 19, 24, 29, 31],
       [ 1,  6,  8, 11, 12, 12, 18, 27, 33, 40]])

In [38]:
array_1.sort(axis=1)
array_1

array([[ 1,  3, 13, 20, 23, 25, 29, 30, 32, 33],
       [ 3,  7,  9, 11, 22, 23, 24, 27, 29, 33],
       [ 2,  4,  4,  9, 24, 24, 25, 26, 30, 37],
       [ 1,  1,  9, 10, 21, 23, 27, 29, 31, 35],
       [ 0,  6,  7,  9, 13, 16, 23, 24, 34, 36],
       [12, 12, 16, 22, 31, 32, 35, 35, 37, 38],
       [13, 14, 19, 26, 30, 32, 34, 34, 35, 35],
       [ 5,  5,  9, 16, 20, 27, 33, 33, 40, 40],
       [ 5,  7, 15, 17, 18, 22, 23, 37, 40, 40],
       [ 6,  9,  9, 19, 21, 22, 25, 26, 32, 33]])

In [41]:
array_2

array([[ 2,  8, 17,  9, 30, 17, 11,  5, 19,  4],
       [26, 12, 20,  5, 11, 23,  2, 30, 30, 23],
       [16, 16, 17,  3,  3,  5, 25,  9, 12, 11],
       [ 6, 27,  4, 25,  2, 14, 29, 12, 16, 28],
       [21,  5,  9, 14,  0,  7,  9, 30, 15, 10],
       [ 4,  5,  3, 16, 26, 26,  6, 23, 30, 25],
       [24,  0, 13,  6,  2, 16, 27,  1, 13,  3],
       [24,  3, 12, 30, 10, 12,  3, 14, 17, 15],
       [12, 24, 30, 22, 15,  9, 11, 11, 29,  0],
       [18,  7, 15, 29, 28, 29, 14, 17,  6, 12]])

In [42]:
array_2.sort(axis=0)
array_2

array([[ 2,  0,  3,  3,  0,  5,  2,  1,  6,  0],
       [ 4,  3,  4,  5,  2,  7,  3,  5, 12,  3],
       [ 6,  5,  9,  6,  2,  9,  6,  9, 13,  4],
       [12,  5, 12,  9,  3, 12,  9, 11, 15, 10],
       [16,  7, 13, 14, 10, 14, 11, 12, 16, 11],
       [18,  8, 15, 16, 11, 16, 11, 14, 17, 12],
       [21, 12, 17, 22, 15, 17, 14, 17, 19, 15],
       [24, 16, 17, 25, 26, 23, 25, 23, 29, 23],
       [24, 24, 20, 29, 28, 26, 27, 30, 30, 25],
       [26, 27, 30, 30, 30, 29, 29, 30, 30, 28]])