#Numpy, libreria para ciencia de datos

In [1]:
import numpy as np 
#pip install numpy

In [3]:
array_1d=np.array([1,4,3])
print(array_1d)


[1 4 3]


In [5]:
array_1d

array([1, 4, 3])

In [7]:
array_2d=np.array([(1,4,2),(5,2,3)])
array_2d

array([[1, 4, 2],
       [5, 2, 3]])

In [10]:
array_3d=np.array([[(1.6,4.5,2),(1,5.8,9)],[(7,5,9.3),(8,1.4,3)],[(3,5,3),(7,2,9)]],dtype=float)
array_3d

array([[[1.6, 4.5, 2. ],
        [1. , 5.8, 9. ]],

       [[7. , 5. , 9.3],
        [8. , 1.4, 3. ]],

       [[3. , 5. , 3. ],
        [7. , 2. , 9. ]]])

In [11]:
print(array_3d)

[[[1.6 4.5 2. ]
  [1.  5.8 9. ]]

 [[7.  5.  9.3]
  [8.  1.4 3. ]]

 [[3.  5.  3. ]
  [7.  2.  9. ]]]
