#Numpy, libreria para ciencia de datos

In [12]:
import numpy as np 
#pip install numpy

In [13]:
array_1d=np.array([1,4,3])
print(array_1d)


[1 4 3]


In [14]:
array_1d

array([1, 4, 3])

In [15]:
array_2d=np.array([(1,4,2),(5,2,3)])
array_2d

array([[1, 4, 2],
       [5, 2, 3]])

In [16]:
array_3d=np.array([[(1.6,4.5,2),(1,5.8,9)],[(7,5,9.3),(8,1.4,3)],[(3,5,3),(7,2,9)]],dtype=float)
array_3d

array([[[1.6, 4.5, 2. ],
        [1. , 5.8, 9. ]],

       [[7. , 5. , 9.3],
        [8. , 1.4, 3. ]],

       [[3. , 5. , 3. ],
        [7. , 2. , 9. ]]])

In [17]:
print(array_3d)

[[[1.6 4.5 2. ]
  [1.  5.8 9. ]]

 [[7.  5.  9.3]
  [8.  1.4 3. ]]

 [[3.  5.  3. ]
  [7.  2.  9. ]]]


#Creando Arrays

In [20]:
#De ceros con 3 filas y 4 columnas
array_ceros=np.zeros((3,4))
array_ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
#De unos con 2 dimensiones 4 filas 5 columnas
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [23]:
#Intervalo y saltos
np.arange(12,31,2)

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [24]:
#Intervalo y divisiones
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

In [26]:
#Valor dado
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [27]:
#Matriz identidad, diagonal de unos
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
#Valores aleatorios entre 0 y 1
np.random.random((4,4))

array([[0.66844722, 0.56544292, 0.70885921, 0.93736475],
       [0.38383995, 0.56864345, 0.34004529, 0.34409749],
       [0.55815169, 0.09465649, 0.74299246, 0.81515689],
       [0.07886243, 0.75957885, 0.19707545, 0.05286874]])

In [37]:
#Vacio de 4 filas y 3 columnas
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])