In [17]:
import numpy as np

Crea un array con elementos del 20 al 60 inclusives

In [18]:
array = np.arange(20,61,1)
array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60])

Crea un array de una dimension con 15 elementos de unos, luego cambiar el tercer elemento a 99

In [19]:
array = np.ones((1,15))
array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
array[0,2]=99
array

array([[ 1.,  1., 99.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.]])

Crea una matriz de 6 * 6 de ceros

In [21]:
array = np.zeros((6,6))
array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

Convertir el tipo de datos anterior a entero





In [22]:
array.dtype.name

'float64'

In [23]:
array.dtype="int64"
array.dtype.name

'int64'

In [24]:
array

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

Crea un array de numeros enteros del 1 al 20 inclusives, con 4 filas y 3 columnas, muestra el valor de la segunda fila y primera columna

In [25]:
array = np.random.randint(1,21,size=12)
array

array([ 3,  1,  9,  6, 15, 19, 19,  8, 12, 17, 15,  5])

In [26]:
array = array.reshape(4,3)
array

array([[ 3,  1,  9],
       [ 6, 15, 19],
       [19,  8, 12],
       [17, 15,  5]])

In [27]:
array[1,0]

6

Crea un array con valores del rango 50 a 99 inclusives

In [28]:
array=np.arange(50,100)
array

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

Invierte el array anterior

In [29]:
array[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50])

Crea una matriz 4 * 4 con valores de 1 a 16

In [30]:
array = np.arange(1,17).reshape(4,4)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Encontrar los valores mayores a 6 del array anterior

In [31]:
array_sup_6 = array[array>6]
array_sup_6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

Crear una matriz identidad de 5 * 5

In [32]:
array = np.identity(5)
array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Crear matriz con valores al azar entre 0 y 1 de forma 4x4x4

In [36]:
array = np.random.random((4,4,4))
array

array([[[0.46792579, 0.80543105, 0.48632238, 0.50925258],
        [0.6231334 , 0.10153566, 0.18376603, 0.18064542],
        [0.85663883, 0.55153831, 0.42418603, 0.5153277 ],
        [0.20337045, 0.25327346, 0.60670109, 0.039873  ]],

       [[0.97379699, 0.14985832, 0.35550735, 0.01296495],
        [0.33928645, 0.08695776, 0.26779619, 0.81947732],
        [0.39367715, 0.74535707, 0.68121915, 0.54025828],
        [0.504553  , 0.83423785, 0.87006748, 0.6281623 ]],

       [[0.71334887, 0.49172105, 0.79351014, 0.54753712],
        [0.64642754, 0.88560894, 0.07278026, 0.99507079],
        [0.920198  , 0.91250307, 0.183184  , 0.56130595],
        [0.37105236, 0.89473233, 0.26780755, 0.22917985]],

       [[0.27914614, 0.34049903, 0.60531643, 0.62264336],
        [0.19890604, 0.38684147, 0.40000842, 0.1871246 ],
        [0.4293482 , 0.67223595, 0.44363272, 0.85630668],
        [0.90176705, 0.25792576, 0.14015164, 0.20138009]]])

Indicar valor minimo y maximo del array anterior y su posicion


In [37]:
array.min()

0.012964952721245315

In [38]:
array.argmin()

19

In [39]:
array.max()

0.9950707895556872

In [40]:
array.argmax()

39

Crear 2 arrays al azar y verificar si son iguales

In [41]:
array_1 = np.random.random((5,5))
array_1

array([[0.0058497 , 0.41381705, 0.92278843, 0.19381729, 0.03429331],
       [0.31157397, 0.52481905, 0.31778753, 0.08473261, 0.10486481],
       [0.13938964, 0.33975296, 0.05821981, 0.57937217, 0.19249872],
       [0.20361912, 0.08833188, 0.20064267, 0.82640593, 0.87300572],
       [0.60402185, 0.42845106, 0.60218572, 0.48566552, 0.82482496]])

In [43]:
array_2 = np.random.random((5,5))
array_2

array([[0.63317969, 0.97074645, 0.32770971, 0.58309686, 0.85534331],
       [0.12231531, 0.62789743, 0.05804871, 0.9424767 , 0.78571444],
       [0.70378903, 0.73221241, 0.45202662, 0.86150789, 0.63466714],
       [0.33959459, 0.64705726, 0.57726853, 0.52257362, 0.23458661],
       [0.86543084, 0.21447083, 0.62445299, 0.1892695 , 0.2358719 ]])

In [44]:
array_1==array_2

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [45]:
np.array_equal(array_1,array_2)

False

De uno de los arrays anteriores obten la media y muestra los valores que estan por encima de la media

In [46]:
media = array_1.mean()
media

0.3744292595449141

In [47]:
array_1[array_1>media]


array([0.41381705, 0.92278843, 0.52481905, 0.57937217, 0.82640593,
       0.87300572, 0.60402185, 0.42845106, 0.60218572, 0.48566552,
       0.82482496])

In [48]:
array_1

array([[0.0058497 , 0.41381705, 0.92278843, 0.19381729, 0.03429331],
       [0.31157397, 0.52481905, 0.31778753, 0.08473261, 0.10486481],
       [0.13938964, 0.33975296, 0.05821981, 0.57937217, 0.19249872],
       [0.20361912, 0.08833188, 0.20064267, 0.82640593, 0.87300572],
       [0.60402185, 0.42845106, 0.60218572, 0.48566552, 0.82482496]])