#Numpy, libreria para ciencia de datos

In [1]:
import numpy as np 
#pip install numpy

In [2]:
array_1d=np.array([1,4,3])
print(array_1d)


[1 4 3]


In [3]:
array_1d

array([1, 4, 3])

In [4]:
array_2d=np.array([(1,4,2),(5,2,3)])
array_2d

array([[1, 4, 2],
       [5, 2, 3]])

In [5]:
array_3d=np.array([[(1.6,4.5,2),(1,5.8,9)],[(7,5,9.3),(8,1.4,3)],[(3,5,3),(7,2,9)]],dtype=float)
array_3d

array([[[1.6, 4.5, 2. ],
        [1. , 5.8, 9. ]],

       [[7. , 5. , 9.3],
        [8. , 1.4, 3. ]],

       [[3. , 5. , 3. ],
        [7. , 2. , 9. ]]])

In [6]:
print(array_3d)

[[[1.6 4.5 2. ]
  [1.  5.8 9. ]]

 [[7.  5.  9.3]
  [8.  1.4 3. ]]

 [[3.  5.  3. ]
  [7.  2.  9. ]]]


#Creando Arrays

In [7]:
#De ceros con 3 filas y 4 columnas
array_ceros=np.zeros((3,4))
array_ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
#De unos con 2 dimensiones 4 filas 5 columnas
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [10]:
#Intervalo y saltos
np.arange(12,31,2)

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [11]:
#Intervalo y divisiones
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

In [12]:
#Valor dado
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [13]:
#Matriz identidad, diagonal de unos
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
#Valores aleatorios entre 0 y 1
np.random.random((4,4))

array([[0.75285211, 0.11858646, 0.36126724, 0.45727286],
       [0.25994762, 0.61445816, 0.76870491, 0.91567557],
       [0.85643901, 0.57397506, 0.15088249, 0.40463163],
       [0.59626211, 0.53078446, 0.59686667, 0.35896276]])

In [15]:
#Vacio de 4 filas y 3 columnas
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#Grabar y cargar

In [20]:
#Grabar
#np.save('mi_array',np.random.random((3,3)))
np.save('mi_array_3d',array_3d)

In [21]:
#Cargar
mi_array=np.load('mi_array_3d.npy')
mi_array

array([[[1.6, 4.5, 2. ],
        [1. , 5.8, 9. ]],

       [[7. , 5. , 9.3],
        [8. , 1.4, 3. ]],

       [[3. , 5. , 3. ],
        [7. , 2. , 9. ]]])

In [24]:
#Grabar a fichero de texto
np.savetxt('mi_array.txt',array_2d,delimiter=" ")

In [27]:
#Cargar de fichero de texto
array_2d=np.loadtxt('mi_array.txt')
print(array_2d)

[[1. 4. 2.]
 [5. 2. 3.]]


#Tipos de datos

In [28]:
#Enteros
np.int64

numpy.int64

In [29]:
#Decimal, numero doble precision o de punto flotante
np.float64

numpy.float64

In [30]:
#Complejos
np.complex_

numpy.complex128

In [32]:
#Boolean
np.bool_

numpy.bool_

In [33]:
#Objetos
np.object_

numpy.object_

In [34]:
#Cadenas
np.string_

numpy.bytes_

In [35]:
np.unicode_

numpy.str_