In [1]:
import numpy as np

Resolver el siguiente sistema de ecuaciones, usando numpy

    x + 3y = 9

    6x + 3y = 5

In [2]:
a=np.array([[1,3],[6,3]])
a

array([[1, 3],
       [6, 3]])

In [3]:
b=np.array([9,5])
b

array([9, 5])

In [4]:
np.linalg.solve(a,b)

array([-0.8       ,  3.26666667])

In [6]:
rdo=-0.8*6+3*3.266666
rdo


4.999997999999998